import * as React from "react";
import Avatar from "@mui/material/Avatar";
import Button from "@mui/material/Button";
import CssBaseline from "@mui/material/CssBaseline";
import TextField from "@mui/material/TextField";
import FormControlLabel from "@mui/material/FormControlLabel";
import Checkbox from "@mui/material/Checkbox";
import Link from "@mui/material/Link";
import Grid from "@mui/material/Grid";
import Box from "@mui/material/Box";
import LockOutlinedIcon from "@mui/icons-material/LockOutlined";
import Typography from "@mui/material/Typography";
import Container from "@mui/material/Container";
import { createTheme, ThemeProvider } from "@mui/material/styles";
import Head from "next/head";
import { SchoolTwoTone } from "@mui/icons-material";
import Router from "next/router";

const theme = createTheme();

export default function SignIn() {
  const handleSubmit = (event) => {
    event.preventDefault();
    const data = new FormData(event.currentTarget);
    console.log({
      email: data.get("email"),
      password: data.get("password"),
    });
  };

  const router = Router;

  function navigator(index) {
    //1 teacher , 2 student  // 3 student signup
    const locals = localStorage.getItem("tokens");

    if (index == 0) {
      router.push("/teacherlogin");
    } else if (index == 1) {
      router.push("/studentlogin");
    } else if (index == 2) {
      router.push("/studentsignup");
    }
  }

  return (
    <div>
      <Head>
        <title>Amin HomeWorks app</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        {/* <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
        />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/icon?family=Material+Icons"
        /> */}
      </Head>

      <ThemeProvider theme={theme}>
        <Container component="main" maxWidth="xs" sx={{}}>
          <CssBaseline />
          <Box
            sx={{
              marginTop: 8,
              display: "flex",
              flexDirection: "column",
              alignItems: "center",
              bgcolor: "primary",
            }}
          >
            <Avatar sx={{ m: 1, bgcolor: "secondary" }}>
              <SchoolTwoTone />
            </Avatar>
            <Typography component="h1" variant="h5">
              Welcome to the Homework system
            </Typography>
            <Box
              component="form"
              onSubmit={handleSubmit}
              noValidate
              sx={{ mt: 1 }}
            >
              <Button
                fullWidth
                variant="contained"
                sx={{ mt: 3, mb: 2 }}
                onClick={() => {
                  //  router.push("/teacherlogin");
                  navigator(0);
                }}
              >
                TEACHER
              </Button>

              <Button
                fullWidth
                variant="contained"
                color="success"
                sx={{ mt: 3, mb: 2 }}
                onClick={() => {
                  //  router.push("/studentlogin");
                  navigator(1);
                }}
              >
                STUDENT
              </Button>

              <Button
                fullWidth
                variant="contained"
                color="warning"
                sx={{ mt: 3, mb: 2 }}
                onClick={() => {
                  //    router.push("/studentsignup");
                  navigator(2);
                }}
              >
                STUDENT SIGNUP
              </Button>
              <Grid container>
                <Typography
                  component="h6"
                  variant="h6"
                  style={{ textAlign: "center" }}
                >
                  please choose , you are entering as Teacher or Student{" "}
                </Typography>
              </Grid>
            </Box>
          </Box>
        </Container>
      </ThemeProvider>
    </div>
  );
}
